drop table grievance if exists;

create table grievance (memberId bigint(20) generated by default as identity (start with 1),
memberName varchar(200),requestType varchar(200), comments varchar(200), primary key (memberId));