drop table user if exists;

create table user (id bigint generated by default as identity (start with 1), emailAddress varchar(255), 
lastAccessTime timestamp, login_name varchar(255), password varchar(255), registrationDate date, 
verified bit, primary key (id))
