drop table user if exists;

create table user (id bigint generated by default as identity (start with 1), emailAddress varchar(255),
lastAccessTime timestamp, login_name varchar(255), password varchar(255), registrationDate date,
verified bit, primary key (id));

    CREATE TABLE `user` (
          `id` bigint(20) NOT NULL AUTO_INCREMENT,
          `emailAddress` varchar(765) DEFAULT NULL,
          `lastAccessTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
          `login_name` varchar(765) DEFAULT NULL,
          `password` varchar(765) DEFAULT NULL,
          `registrationDate` date DEFAULT NULL,
          `verified` bit(1) DEFAULT NULL,
          PRIMARY KEY (`id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1

    create table `signin_details` (
	`sign_id` bigint(20) NOT NULL AUTO_INCREMENT,
	`login_name` varchar (450) DEFAULT 'NULL',
	`password` varchar (450) DEFAULT 'NULL',
	`first_name` varchar (450) DEFAULT 'NULL',
	`last_name` varchar (450) DEFAULT 'NULL',
	`email_address` varchar (450) DEFAULT 'NULL',
	`repeat_email` varchar (450) DEFAULT 'NULL',
	`birthday` varchar (450) DEFAULT 'NULL',
	`month` varchar (450) DEFAULT 'NULL',
	`year` year (4) DEFAULT 'NULL',
	`gender` varchar (450) DEFAULT 'NULL',
	`city` varchar (450) DEFAULT 'NULL',
	`country_region` varchar (450) DEFAULT 'NULL',
	`language` varchar (450) DEFAULT 'NULL',
	`skype_name` varchar (450) DEFAULT 'NULL',
	`skype_password` varchar (450) DEFAULT 'NULL',
	`repeat_password` varchar (450) DEFAULT 'NULL',
	`skypeName_helper` varchar (450) DEFAULT 'NULL',
         PRIMARY KEY (`sign_id`)
);